import { STEMS, tenGod, type Chart } from './core';
import type { Words, buildStructureReading } from './reading';
import type { EverydayContext } from './everyday';
import type { RoleFact } from './topics';
import type { DepthSection } from './classics';

const w = (zh: string, en: string): Words => ({ zh, en });
const pos = ['年', '月', '日', '时'];
const posEn = ['year', 'month', 'day', 'hour'];
const family = ['比劫', '食伤', '财星', '官杀', '印星'];
const families = [
  ['比肩', '劫财'],
  ['食神', '伤官'],
  ['正财', '偏财'],
  ['正官', '七杀'],
  ['正印', '偏印'],
];
const describe = (r: RoleFact) =>
  w(
    `${pos[r.position]}${r.layer === 'visible' ? '干' : '支藏'}${r.stem}（${r.god}${r.layer === 'main' ? '，本气' : ''}）`,
    `${posEn[r.position]} ${r.layer === 'visible' ? 'stem' : 'hidden stem'} ${r.stem} (${r.god}${r.layer === 'main' ? ', main qi' : ''})`,
  );
const list = (items: Words[], none = w('已知字位中未见', 'Not found in supplied positions')) =>
  w(
    items.length ? items.map((x) => x.zh).join('；') : none.zh,
    items.length ? items.map((x) => x.en).join('; ') : none.en,
  );
const section = (
  title: Words,
  paragraphs: Words[],
  basis?: Words,
  source?: DepthSection['source'],
): DepthSection => ({ title, paragraphs, basis, source });

// These are original modern analogies, not quotations or measured personal traits.
const workDetails: Record<
  string,
  {
    title: Words;
    meaning: Words;
    scene: Words;
    condition: Words;
    groups: number[];
    source: DepthSection['source'];
  }
> = {
  expression_authority: {
    title: w(
      '食伤与官杀：自己的办法，遇到外部的标准',
      'Output and authority: methods meet standards',
    ),
    meaning: w(
      '“食伤”合指食神、伤官，是日主所生的五行；“官杀”合指正官、七杀，是克制日主的五行。前者可以借喻把想法做出来，后者可以借喻规则、考核和责任。两类线索同见，工作章便关注“我觉得怎样做更好”和“别人要求我怎样做”之间的关系。',
      'Output means phases generated by the day stem; authority means phases controlling it. Our modern analogy puts making and expression beside standards, evaluation and responsibility.',
    ),
    scene: w(
      '比如同样收到“按模板完成”的任务，有人先想怎样避免出错，有人先想模板哪里能改。这一组合采用后一种与规则碰面的情境：顺畅时，是把改进变成可检验的成果；不顺时，是对方法的讨论被听成对人的反对。这里描述的是一种可能的互动方式，不是说你一定不服管。',
      'For a template-based task, the analogy is someone who sees a better method while working within a required standard. This can become a testable improvement, or a disagreement about methods can be heard as personal opposition. It is a possible interaction, not a claim of defiance.',
    ),
    condition: w(
      '这还不能直接叫“伤官见官”：必须分清实际出现的是食神还是伤官、正官还是七杀，再看月令、印星及其他配置。把四个不同的名字压成一句“容易得罪领导”，省掉了最关键的条件。',
      'This does not establish the specific pattern “Hurting Officer meets Direct Officer.” Exact roles, month context, resource and other relationships still matter.',
    ),
    groups: [1, 3],
    source: 'month',
  },
  authority_resource: {
    title: w('官印相生：要求能否转成你的底气', 'Authority and resource: demands and support'),
    meaning: w(
      '官杀是“克我”，印星是“生我”。在五行相生的链条里，官杀所属五行能生印，印又能生日主，所以有“官印相生”这条读法。通俗说，它关心的不只是责任重不重，还关心责任背后有没有知识、资格、经验或组织支持。',
      'Authority controls the day phase; resource generates it. Authority can generate resource, which in turn supports the day phase. Our analogy asks whether responsibility is accompanied by knowledge, experience, credentials or institutional support.',
    ),
    scene: w(
      '比如接手一个新岗位，同时有明确规则、前辈带教和可查资料，压力就可能逐渐变成胜任感。另一种表现是很会按标准准备，却迟迟不敢在没有标准答案时做决定。这两面都属于“凭准备和依据获得确定感”的风格，并不是命盘已经确认你有学历或贵人。',
      'A new role with clear rules, mentoring and documentation illustrates demands becoming competence. Another expression is careful preparation coupled with hesitation when no standard answer exists. Neither is evidence that the reader has a degree or a benefactor.',
    ),
    condition: w(
      '官与印同时出现，只能说存在这条关系线索。若只有要求，没有足够承接条件，就不能把“相生”理解成一路顺利；本版也尚未判断完整官印格局是否成立。',
      'Co-presence identifies a possible chain. Demands without sufficient support do not become effortless progress; this app does not establish a complete formal pattern.',
    ),
    groups: [3, 4],
    source: 'roles',
  },
  output_wealth: {
    title: w(
      '食伤生财：会做、做出来、被需要，是三件事',
      'Output generating wealth: ability, delivery and demand',
    ),
    meaning: w(
      '食神、伤官是日主所生，财星是日主所克；沿五行相生次序，食伤又能生财。“生财”因此说的是一条关系路径。换成生活语言，就是能力有了作品或服务，作品又对接到别人的需要，才谈得上交换和回报。',
      'Output is generated by the day phase; wealth is controlled by it. Output can generate wealth in the phase sequence. The modern analogy is a skill becoming a deliverable that meets another person’s need, creating the possibility of exchange.',
    ),
    scene: w(
      '例如同样会摄影，一个人主要追求照片表达得好，另一个人还会琢磨客户为什么需要这组照片。这里的风格更接近把“做好”和“有用”连着想。顺畅时，技术和需求互相促进；卡住时，可能做了很多却没有被认可，也可能太在意回报而失去创作耐心。',
      'For photography, this analogy links making a strong image with understanding why someone needs it. Skill and demand may reinforce each other; possible friction includes much work without recognition, or immediate rewards crowding out creative patience.',
    ),
    condition: w(
      '古文紧接着还讨论财是否有根、身与食是否能承接，不是只要两个名字齐了就算“食神生财格”。本盘若出现伤官，也不能把只论食神的一段原文当作已经完成论证。这里保留“食伤与财并见”的结论。',
      'The source goes on to consider wealth roots and the condition of day stem and output. Two names alone do not establish a Food-God-generating-Wealth pattern, and a Food God passage does not automatically cover Hurting Officer.',
    ),
    groups: [1, 2],
    source: 'output',
  },
  authority: {
    title: w(
      '正官与七杀：都是要求，侧重点不同',
      'Direct Officer and Seven Killings: two forms of demand',
    ),
    meaning: w(
      '官杀来自克制日主的五行，正官与七杀再按阴阳关系分开。传统名称听起来有褒贬，但“七杀”不是灾祸通知，“正官”也不是官职证明。本章把这一类共同理解为外界标准、职责和压力进入主要视野。',
      'Both authority roles control the day phase and differ by polarity. Seven Killings is not a disaster notice and Direct Officer is not proof of a job title. The shared modern theme is standards, duties and demands.',
    ),
    scene: w(
      '这类风格的例子，是接到任务先弄清目标、期限和结果由谁负责；有把事情守住的一面，也可能把每次反馈都当成考核。能否在规则里做得舒展，还取决于权限和支持是否跟得上。',
      'An illustrative style asks about targets, deadlines and accountability. It may bring reliability, or make each comment feel like an evaluation. Authority and available support influence the real experience.',
    ),
    condition: w(
      '有官杀不等于适合某个固定职业，更不等于能升职。若要按传统方法继续细论，还要区分正官、七杀及它们与食伤、印星的配合，不能仅凭名称排职业清单。',
      'Authority roles do not determine a profession or promotion. A fuller traditional reading would distinguish exact roles and their relationships with output and resource.',
    ),
    groups: [3],
    source: 'month',
  },
  output: {
    title: w('食神与伤官：把内在能力变成外在表达', 'Output: making ability visible'),
    meaning: w(
      '“我生者”为食伤，指日主向外生出的五行关系。“泄”在这里是气的流出，不是泄气、虚弱或泄密。现代解读借它观察表达、制作、解决问题的方式；食神和伤官有区别，本章先解释它们共有的输出主题。',
      'Output is the phase generated by the day phase. “Draining” here means symbolic outward flow, not illness or discouragement. Our analogy concerns explaining, making and solving, while retaining the distinction between the two output roles.',
    ),
    scene: w(
      '比如面对一个难题，比起反复证明“我懂”，这种风格更容易通过讲明白、做出样品来建立存在感。长处可能是把抽象东西变得可见；卡点可能是不断改进表达，却没有确认别人究竟需要什么。',
      'A possible expression is demonstrating or explaining something instead of asserting expertise. Making an abstract idea visible can be a strength; refining it without checking its audience can be a point of friction.',
    ),
    condition: w(
      '食伤显著还不等于能变现。有没有财星承接、有没有印星与根气支持持续输出，是另外的问题；所以工作章的表达线索不能直接复制成财运结论。',
      'Prominent output does not establish income. Wealth as a possible outlet and resource or roots as support are separate considerations.',
    ),
    groups: [1],
    source: 'output',
  },
  resource: {
    title: w('正印与偏印：支持从哪里来，又怎样用起来', 'Resource: receiving and using support'),
    meaning: w(
      '印星指生日主的五行，正印、偏印再按阴阳分开。古书用印绶、父母等名称来比拟荫护和支持。现代读法把范围放在学习、资料、方法、经验和他人的帮助；不能由此反推家庭条件一定好。',
      'Resource generates the day phase, with direct and indirect forms distinguished by polarity. Historical names use protection and parenthood as analogies. Our modern reading concerns learning, methods, experience and help, without asserting family circumstances.',
    ),
    scene: w(
      '例如遇到陌生任务，有人边做边试，有人先找案例、看说明、问有经验的人。这里采用后一种“先理解再行动”的风格。准备充分时，能少走弯路；准备变成拖延时，则可能总觉得还缺一份资料才可以开始。',
      'For an unfamiliar task, the example is someone who first studies examples and asks experienced people. Preparation may reduce mistakes; it can also become a repeated feeling that one more source is needed before starting.',
    ),
    condition: w(
      '印多不是知识多的实测结果，也不是“必有贵人”。支持能不能转为自己的本事，还要结合输出和实际练习；本盘只提供支持关系的符号线索。',
      'Resource roles do not measure knowledge or promise a benefactor. Turning support into ability also involves output and actual practice.',
    ),
    groups: [4],
    source: 'roles',
  },
  wealth: {
    title: w('财星在工作中：看资源与结果怎样对得上', 'Wealth at work: resources and results'),
    meaning: w(
      '财是日主所克的五行。“克”在这里指制约、使用的关系，并不是讨厌或伤害。因此工作章谈财，不只是在谈钱，也借它观察时间、人手、材料和目标之间怎样安排。',
      'Wealth is the phase controlled by the day phase. Control here describes a symbolic relation of use and constraint. At work, our analogy includes time, people, materials and results, not just money.',
    ),
    scene: w(
      '比如讨论一个方案时，这种风格可能较快问到“要多少投入、谁来做、最后得到什么”。长处是把想法落到现实条件；卡点是把太多条件都接到自己身上，或者对短期看不到回报的事情失去耐心。',
      'In a project discussion, an illustrative response asks about inputs, ownership and outcomes. Practicality may help; taking responsibility for every constraint or losing patience with delayed results may create friction.',
    ),
    condition: w(
      '看得到资源议题，不代表已经有资源可用。财星位置和承接条件仍要一起读；“财多”不能直接翻译为收入多、管理能力强或适合创业。',
      'A resource theme does not establish resources available in life. Positions and support still matter; more wealth symbols do not measure income, management ability or entrepreneurial fit.',
    ),
    groups: [2],
    source: 'wealth',
  },
  peer: {
    title: w('比肩与劫财：同一阵营，也可能意见相左', 'Peers: shared ground and competing views'),
    meaning: w(
      '比肩、劫财都与日主五行相同，再按阴阳区分。“劫财”是关系名称，不能照字面理解成钱一定被抢。本版没有命中前面更明确的工作组合，因此用自主、同伴与分工作为保留式观察入口。',
      'Peer roles share the day phase and differ by polarity. Rob Wealth is a role name, not a prediction of theft. This is the fallback work theme when the app finds none of its higher-priority combinations.',
    ),
    scene: w(
      '例如和熟悉的人一起做事，可能默契来得快，也可能因为都很有主意而难以让步。能独立判断是一面，能否容纳别人采用不同方法是另一面。这种对照用来帮助理解风格，并不证明你爱争强或朋友会拖累你。',
      'Working with familiar peers can bring quick understanding or competing views. Independence and accepting another method are two sides of the example, without asserting competitiveness or unreliable friends.',
    ),
    condition: w(
      '比劫能帮身，也可能与财星形成竞争议题，不能永远只取一个方向。尤其没有完整时柱时，“未命中”只是已知信息下的结果，不是你的人生只有同伴这一条线。',
      'Peers can be read as support or as competition around resources. Incomplete input makes this fallback particularly tentative; it does not reduce a life to one theme.',
    ),
    groups: [0],
    source: 'roots',
  },
};

export function buildDepth(
  chart: Chart,
  report: ReturnType<typeof buildStructureReading>,
  facts: RoleFact[],
  context: EverydayContext,
): Record<string, DepthSection[]> {
  const f = report.features,
    annual = report.annual;
  const selected = (groups: number[], salient = false) =>
    facts.filter(
      (r) =>
        groups.some((g) => families[g].includes(r.god)) &&
        (!salient || r.layer === 'visible' || (r.position === 1 && r.layer === 'main')),
    );
  const roots = list(
    f.roots.map((r) =>
      w(
        `${pos[r.position]}支${r.branch}藏${r.stem}（${r.main ? '本气' : '余气/中气'}）`,
        `${posEn[r.position]} branch ${r.branch} contains ${r.stem} (${r.main ? 'main' : 'additional'} qi)`,
      ),
    ),
  );
  const strength = {
    supported: w(
      '本版的简化筛查发现季节、根与显干支持同时出现，因此保留“支持线索较齐”的读法；这不是已经定了身旺格。',
      'Our limited screen finds aligned seasonal, root and visible-stem support; this does not establish a formal strong pattern.',
    ),
    drained: w(
      '本版的简化筛查没有找到同类根，月令也不直接帮扶，因此先关注“承接条件是否不足”；不据此认定人软弱或做不成事。',
      'Our limited screen finds no same-phase roots and no direct seasonal support, so symbolic support remains a question. This says nothing about courage or real ability.',
    ),
    mixed: w(
      '支持与消耗线索并不单一，本版保留两面，不把它硬定为身强或身弱，也不把“混合”当成恰好平衡。',
      'Support and drain are mixed. We retain both possibilities rather than declare strength, weakness or perfect balance.',
    ),
    withheld: w(
      `本盘${!f.complete ? '缺少时柱' : f.concentrated ? '五行较集中' : '月支本气属土'}，超出这套简化筛查适合判断的范围，因此暂不定身强身弱。`,
      `This chart ${!f.complete ? 'has no hour pillar' : f.concentrated ? 'has concentrated phases' : 'has Earth as main month qi'}, so our limited strength screen withholds judgment.`,
    ),
  }[f.strength];
  const rootBasis = w(
    `同类根：${roots.zh}。年、月、时显干中，帮扶线索${f.support.length}处，输出、财或官杀线索${f.drain.length}处；这里只列位置，不按个数直接比强弱。${!f.complete ? '时柱未知，未列出的信息不算不存在。' : ''}`,
    `Same-phase roots: ${roots.en}. Visible non-day stems: ${f.support.length} supportive and ${f.drain.length} output/wealth/authority positions. These are positions, not strength weights.${!f.complete ? ' The hour is unknown, not absent from life.' : ''}`,
  );
  const work = workDetails[context.career];
  const overview = [
    section(
      w(
        '日主与月令：先确定“从谁的角度、在什么背景下看”',
        'Day stem and month: reference and setting',
      ),
      [
        w(
          `日主是日柱天干，本盘为${chart.dayMaster}${f.day}，相当于整张关系图的观察中心；它不是“你只属于一种五行”。月令是出生月的地支，提供节气背景。本盘月支为${chart.pillars[1].branch}，本气${f.monthMain.stem}，对日主是${f.monthMain.god}。所以开头先谈${family[f.monthRelation]}主题，而不是随便抽一句性格评语。`,
          `The day stem ${chart.dayMaster} (${f.day}) is the reference for this relationship map, not a claim that a person consists of one phase. The month branch ${chart.pillars[1].branch}, with main qi ${f.monthMain.stem} (${f.monthMain.god}), supplies the seasonal starting point.`,
        ),
        w(
          '这句古文里的“用神”以月令立论，接着讨论怎样配合日干、辨别格局。它与日常说的“找一种能补我的五行”并非同一个简化问题。因此看到缺某个字，就建议补某种颜色或物品，跳过了原文的判断过程。',
          'In this passage, yong shen begins with the month and its relationship to the day stem and pattern. It is not simply a missing phase to repair with a color or object.',
        ),
      ],
      undefined,
      'month',
    ),
    section(
      w('通根与透干：有字出现，还要看有没有落脚处', 'Roots and exposure: presence and grounding'),
      [
        w(
          '地支里还藏着天干，叫“藏干”。其中与日主同五行的线索叫“通根”，可把它想成树有地下的根；藏着的某个天干又在年、月、时天干出现，本版会标出“透干”。一个关注有没有根基，一个关注同一线索是否显露，不能把两个名字混为一谈。',
          'Branches contain hidden stems. Same-phase hidden stems are recorded as roots, like a tree’s grounding. When an exact hidden stem also appears in a visible non-day stem, the app records exposure. Grounding and exposure answer different questions.',
        ),
        w(
          '“干多不如根重”提醒读者，数出几个木、几个金还不够；位置、本气或其他藏气、季节都影响传统读法。本版把这些依据列出，但尚未计算根在合冲后的变化。',
          'The short excerpt stresses that visible counts alone are insufficient; position, main or additional qi and season matter. This app lists those facts without resolving changes to roots after combinations or clashes.',
        ),
      ],
      w(
        `${rootBasis.zh} 同字透干：${list(f.exposed.map((x) => w(`${pos[x.position]}支${x.branch}中的${x.stem}`, `${x.stem} from ${posEn[x.position]} branch ${x.branch}`))).zh}。`,
        `${rootBasis.en} Exact-stem exposure: ${list(f.exposed.map((x) => w('', `${x.stem} from ${posEn[x.position]} branch ${x.branch}`))).en}.`,
      ),
      'roots',
    ),
    section(
      w(
        '身强身弱：说的是关系承接，不是人的高低',
        'Strength: a symbolic condition, not personal worth',
      ),
      [
        strength,
        w(
          '把命盘比作一张工作台：“支持”像支架，“输出、财、官杀”像台面上不同的任务。判断关心的是这套配置怎样配合，不是任务越少越好，也不是支架越多越好。这个比喻只是帮助理解；你的执行力、性格和身体状况，不能靠这里的强弱标签测出来。',
          'As an explanatory metaphor, support resembles a workbench frame and output, wealth and authority resemble different tasks on it. The question is how the arrangement fits together, not whether more support is always better. This metaphor does not measure personality, ability or health.',
        ),
      ],
    ),
  ];
  const workSections = [
    section(
      work.title,
      [work.meaning, work.scene],
      list(selected(work.groups, true).map(describe)),
      work.source,
    ),
    section(
      w('这条线索能走多远，还要看根与承接', 'What supports this theme?'),
      [work.condition, strength],
      rootBasis,
    ),
  ];

  return { overview, work: workSections, ...otherDepth(chart, report, facts, context, strength) };
}

function otherDepth(
  chart: Chart,
  report: ReturnType<typeof buildStructureReading>,
  facts: RoleFact[],
  context: EverydayContext,
  strength: Words,
): Record<string, DepthSection[]> {
  const wealth = facts.filter((r) => families[2].includes(r.god));
  const visible = list(wealth.filter((r) => r.layer === 'visible').map(describe));
  const hidden = list(wealth.filter((r) => r.layer !== 'visible').map(describe));
  const direct = STEMS.find((s) => tenGod(chart.dayMaster, s).name === '正财')!;
  const indirect = STEMS.find((s) => tenGod(chart.dayMaster, s).name === '偏财')!;
  const moneyMode = {
    direct: w(
      '正财进入主要线索，因此这里侧重约定、投入和回报之间较明确的对应。现代例子可以是按约交付、按约收款；这只是帮助理解，正财并不等于工资，也不证明收入稳定。',
      'Direct wealth is prominent, so the analogy emphasizes defined inputs and agreed returns. Agreed delivery and payment are examples, not a claim that Direct Wealth literally means a stable salary.',
    ),
    indirect: w(
      '偏财进入主要线索，因此这里侧重资源流转与机会之间的协调。现代例子可以是一次合作里连接需求、人手和材料；这不等于“横财运”，更不说明应该去投机。',
      'Indirect wealth is prominent, so the analogy emphasizes coordinating resources and opportunities: for example, matching demand, people and materials for a collaboration. This does not mean windfalls or speculative success.',
    ),
    both: w(
      '正财与偏财都进入主要线索，所以这张盘不能只用“稳定型”或“机会型”概括。对应到现实，可以把确定的安排和临时的合作分开观察；这不是已经确认你有两份收入。',
      'Both roles are prominent, so a single stable-versus-opportunity label is inadequate. Regular arrangements and temporary collaborations are separate analogies, not evidence of two income sources.',
    ),
    hidden: w(
      '财星只在其他藏干中出现，没有进入本版优先采用的显干或月支本气。因此这里只保留资源关系的线索，暂不把它写成明确财务风格。“藏财”也不等于暗中有钱、晚年才发财。',
      'Wealth appears only in other hidden stems, outside the app’s prominent positions. A resource relation is recorded without a definite financial portrait; hidden wealth does not mean secret money or delayed riches.',
    ),
    absent: w(
      '已知字位没有找到财星，因此本版暂不选财务风格。没有这个符号，不等于没有工作、收入或资产；若时辰未知，还要保留缺失时柱可能带来新信息。',
      'No wealth role is found in supplied positions, so no financial portrait is chosen. This does not establish a lack of work, income or assets; an unknown hour may add symbolic information.',
    ),
  }[context.money as 'direct' | 'indirect' | 'both' | 'hidden' | 'absent'];
  const output = list(facts.filter((r) => families[1].includes(r.god)).map(describe));
  const peers = list(facts.filter((r) => families[0].includes(r.god)).map(describe));
  const moneySections = [
    section(
      w(
        '正财、偏财：先读关系，再谈生活里的钱',
        'Direct and indirect wealth: relation before income',
      ),
      [
        w(
          `“我克者为财”：以本盘${chart.dayMaster}为观察中心，${direct}是正财，${indirect}是偏财，区别来自阴阳配对；换一个日主，同一个字的十神名称也可能改变。古文“使用之物”说明财的含义比钞票广，也涉及人如何支配外部资源。`,
          `Relative to this day stem ${chart.dayMaster}, ${direct} is Direct Wealth and ${indirect} is Indirect Wealth, distinguished by polarity. A different day stem can change a symbol’s role. The historical term concerns resources subject to use, beyond cash alone.`,
        ),
        moneyMode,
      ],
      undefined,
      'wealth',
    ),
    section(
      w('透财与藏财：位置不同，不是余额不同', 'Visible and hidden wealth: positions, not balances'),
      [
        w(
          '“透财”是财星出现在天干，“藏财”是它位于地支藏干。月支本气又有季节背景，所以本版将它与显干一起优先看。这样区分，是为了交代为什么同样有一个财字，两张盘的讲法不同；不是把藏着的字换算成“未到账的钱”。',
          'Visible wealth appears in stems; hidden wealth is contained in branches. Main month qi also supplies seasonal context and receives priority here. These distinctions explain different symbolic readings, not different account balances or unpaid invoices.',
        ),
      ],
      w(
        `显干：${visible.zh}。藏干：${hidden.zh}。${!context.complete ? '本盘时柱未知，以上只覆盖已知三柱。' : ''}`,
        `Visible: ${visible.en}. Hidden: ${hidden.en}.${!context.complete ? ' Only the three known pillars are covered.' : ''}`,
      ),
    ),
    section(
      w('生财与承财：机会怎样形成，自己能否接住', 'Generating wealth and supporting the exchange'),
      [
        w(
          '传统读法还会问：食伤能否接到财这一环？日主有没有根与印比支持？比劫出现时，是帮手还是竞争，还得放回全局。通俗地说，做得出东西、找到需要它的人、承担交付成本，是三个不同问题；某一环的名字出现，不能代替整条链已经走通。',
          'A traditional reading also asks about output-to-wealth links, roots and resource or peer support. Peers can suggest support or competition depending on context. Making something, finding demand and meeting delivery costs are three different questions.',
        ),
        strength,
      ],
      w(
        `食伤线索：${output.zh}。比劫线索：${peers.zh}。这些只是关系位置，没有代入你的收入、支出或资产。`,
        `Output: ${output.en}. Peers: ${peers.en}. These record positions; no income, spending or assets have been inferred.`,
      ),
    ),
  ];
  const day = chart.pillars[2];
  const dayFacts = list(day.hidden.map((h) => w(`${h.stem}（${h.god}）`, `${h.stem} (${h.god})`)));
  const links = chart.relations.filter((r) => r.positions.includes(2));
  const linksText = list(
    links.map((r) =>
      w(
        `${r.positions.map((p) => pos[p] + '支').join('、')}：${r.branches}${r.kind}`,
        `${r.positions.map((p) => posEn[p] + ' branch').join(', ')}: ${r.branches} (${r.kind})`,
      ),
    ),
    w('已知字位中未检出本版支持的日支关系', 'No supported day-branch relationship found'),
  );
  const relationshipScenes = [
    w(
      '日支本气与日主同类，现代类比偏向“亲近中的平等”。比如彼此都希望被尊重、都有决定权时，容易把伴侣当队友；意见不同时，也可能都在等对方先让一步。需要核对的是这种相处节奏是否出现过，而不是先给某个人贴“强势”的标签。',
      'Same-phase main qi suggests our analogy of equality within closeness: teammates with equal say, but sometimes both waiting for the other to yield. It does not assign a domineering personality.',
    ),
    w(
      '日支本气为食伤，现代类比偏向“通过表达确认亲近”。例如愿意分享细节、开玩笑、讲出感受；没有得到回应时，可能觉得被冷落。这里区分的是交流需求和回应方式，不是看出伴侣会不会爱你。',
      'Output main qi suggests the analogy of closeness through expression: sharing details, humor and feelings, with silence sometimes experienced as distance. It does not measure a partner’s love.',
    ),
    w(
      '日支本气为财，现代类比偏向“把在乎放进日常安排”。例如通过分担家务、安排时间或照顾实际需要表达感情。顺畅时，对方感到可靠；不顺时，付出可能变成双方各自计算的账。这是相处方式的例子，不是配偶财产判断。',
      'Wealth main qi suggests care through practical arrangements, time and shared work. This may feel dependable, or become competing accounts of who contributed more. It is not a statement about a partner’s assets.',
    ),
    w(
      '日支本气为官杀，现代类比偏向“有约定才安心”。例如比起临时惊喜，更在意说过的话有没有兑现；关系有边界时容易踏实，规则只由一方制定时容易紧绷。不能由此断定伴侣强势，或你适合被管束。',
      'Authority main qi suggests security through commitments and follow-through. Shared boundaries may help; one-sided rules may create tension. This does not establish a controlling partner or a need to be controlled.',
    ),
    w(
      '日支本气为印，现代类比偏向“被理解和被照顾”。例如压力大时希望有人耐心听完、帮自己理清思路；照顾过多时，也可能一方习惯代办、另一方不容易独立。这是支持方式的两面，不是伴侣年龄、身份或性别的推断。',
      'Resource main qi suggests understanding and care, such as listening through stress. Too much taking over may limit independence. This is an analogy about support, not a partner’s age, identity or gender.',
    ),
  ];
  const relationshipSections = [
    section(
      w(
        '夫妻宫与配偶星：一个讲位置，一个讲关系',
        'Relationship palace and role: position versus relation',
      ),
      [
        w(
          `“日支”是日柱下面的字，本盘为${day.branch}；传统称它为夫妻宫。“配偶星”则是按另一套传统对应选取的十神，两者不是同一个概念。可以把宫看成关系图上的一个位置，把星看成出现在不同位置的关系标签。`,
          `The day branch ${day.branch} is traditionally called the spouse palace. A spouse role is a separately assigned ten-god relation. A palace is a location; a role is a relation that can appear in different locations.`,
        ),
        w(
          '这段古书从古代男命、妻子的框架写起，还带有当时的婚姻观。本版只借它说明“宫与星要分开”，不沿用其中对配偶优劣的评判，也不把大运顺逆选项当成你的伴侣性别。',
          'The source uses a historical male-chart and wife framework. Here it explains the distinction between palace and role; its spouse judgments are not adopted, and cycle convention does not determine a partner’s gender.',
        ),
      ],
      w(
        `日柱${day.text}；日支${day.branch}藏${dayFacts.zh}，本气为${day.hidden[0].god}。`,
        `Day pillar ${day.text}; branch ${day.branch} contains ${dayFacts.en}; main qi is ${day.hidden[0].god}.`,
      ),
      'palace',
    ),
    section(
      w('落到日常：这类相处风格可能怎样表现', 'An everyday illustration of the relationship style'),
      [
        relationshipScenes[context.relationship],
        w(
          '这里只用日支本气提供一个观察角度，其他藏干和现实经历仍可能让表现不同。同一关系里，两个人也可能在不同情境下互换角色；因此上面的分析是待你核对的描述，下面的建议才是在谈可以改变什么。',
          'Main day-branch qi provides one lens; other hidden stems and actual experience can change the picture. People may switch roles in different situations. This is a description to check, with possible changes addressed separately below.',
        ),
      ],
    ),
    section(
      w(
        '合与冲：哪两个位置相遇，比只看一个字更重要',
        'Combinations and clashes: which positions meet?',
      ),
      [
        w(
          context.clash && context.combine
            ? '本盘涉及日支的合与冲同时存在，所以不能用一句“有合就好”盖过另一条关系。'
            : context.clash
              ? '本盘有涉及日支的相冲。冲描述两个地支的对应关系，不能直接写成现实中的争吵或分手。'
              : context.combine
                ? '本盘有涉及日支的相合。合描述一种地支配对，不自动表示感情美满，也不是结婚日期。'
                : '本盘没有检出日支的六合或六冲，不代表相处中没有矛盾，也不代表关系已经稳定。',
          context.clash && context.combine
            ? 'Combination and clash both involve the day branch; neither is erased.'
            : context.clash
              ? 'A day-branch clash is present as a symbolic pair, not evidence of an argument or separation.'
              : context.combine
                ? 'A day-branch combination is present, not proof of happiness or a marriage date.'
                : 'No day-branch pair-combination or clash is detected; this does not establish harmony or stability.',
        ),
        w(
          '古法还要结合月令、喜忌与其他配置，本版只把已检出的关系和位置完整列明，不擅自判定合化成功或冲散根气。换成生活类比，亲近和各自的节奏可能同时存在；类比不能充当已经发生的事实。',
          'A fuller traditional reading considers season and the whole configuration. We list supported pairs without deciding transformation or root cancellation. An analogy of closeness alongside different rhythms remains an analogy, not a report of events.',
        ),
      ],
      linksText,
    ),
  ];
  const healthSections = [
    section(
      w(
        '调候：古人讨论的寒暖，不是体温检查',
        'Climatic balancing is not a body-temperature reading',
      ),
      [
        w(
          '“调候”是在传统命理中结合季节寒暖、燥湿来读五行配合。古文在谈月令用神之后，还提醒需要参看气候，说明“相生”两个字不能脱离季节孤立解释。它讨论的是传统符号体系，并没有测量一个人的器官、激素或体温。',
          'Climatic balancing considers symbolic seasonal warmth, cold, dryness and moisture. The source asks for climatic context alongside month-based relationships. It does not measure organs, hormones or body temperature.',
        ),
        w(
          '比如冬天出生，就在书里遇到“寒”“暖”的说法；这不能顺手翻译为“你体寒”，更不能据此选择药物、补品或治疗。这个区别解释清楚，比给每种五行硬配一个身体毛病更有用。',
          'A winter chart may use words such as cold and warm. That does not establish a bodily condition or select a medicine, supplement or treatment.',
        ),
      ],
      undefined,
      'climate',
    ),
    section(
      w('身弱、偏枯、五行不全，分别在说什么', 'Chart weakness, concentration and missing phases'),
      [
        w(
          '“身弱”是相对支持条件的术语，“偏枯”通常在讨论配置过分偏向一边，“五行不全”只是某些元素没有出现在所查字位。三个说法都不是健康检查结果，不能把“没有某个五行”换成“缺某种营养”，也不能把字数均匀当成身体健康。',
          'Chart weakness concerns symbolic support; concentration concerns an uneven configuration; a missing phase concerns examined symbols. None is a health result, nutrient deficiency or evidence that even counts mean good health.',
        ),
        w(
          '所以这一章的实际情况只从你的回答来：最近的作息是否规律、醒后感觉如何。未填写就保留未知；填写后，提示也只回应你选中的困扰。命理概念留在文化解释里，实际照护从可观察的信息开始。',
          'Actual context in this chapter comes only from your optional sleep responses. Unanswered questions remain unknown, and notes address only the chosen concern. Cultural terminology stays separate from observable health information.',
        ),
      ],
    ),
  ];
  const a = report.annual;
  const linkText = list(
    a.links.map((l) =>
      w(`${l.target}：${l.branches}${l.kind}`, `${l.targetEn}: ${l.branches} (${l.kind})`),
    ),
    w('未检出本版支持的新增配对', 'No supported added pair'),
  );
  const cycleText = a.cycle
    ? w(
        `所选日期位于${a.cycle.pillar}大运，区间${a.cycle.start.slice(0, 10)}至${a.cycle.end.slice(0, 10)}（结束日不含）。`,
        `Selected date falls in ${a.cycle.pillar}, from ${a.cycle.start.slice(0, 10)} to ${a.cycle.end.slice(0, 10)} exclusive.`,
      )
    : w(
        !context.complete
          ? '时柱未知，本次未计算大运。'
          : chart.input.mode === 'pillars'
            ? '手动四柱没有唯一公历时间，本次不指定某日所属大运。'
            : chart.input.direction === 'none'
              ? '你尚未选择大运公式，本次只比较原局与流年。'
              : '所选日期不在已计算的八步大运区间内，本次不指定活动大运。',
        !context.complete
          ? 'No hour pillar: cycles uncalculated.'
          : chart.input.mode === 'pillars'
            ? 'Manual pillars have no unique calendar date, so no dated cycle is assigned.'
            : chart.input.direction === 'none'
              ? 'No cycle convention selected; this compares the natal and annual layers only.'
              : 'The date lies outside the eight calculated cycle intervals; no active cycle is assigned.',
      );
  const timingSections = [
    section(
      w('原局、大运、流年：底图、阶段与年度变化', 'Natal chart, cycle and year: three layers'),
      [
        w(
          '原局是出生时的四柱；大运按所选传统公式排列，约十年一段；流年是每年增加的一柱。古文所说“统观”，就是把后来增加的干支放回原来的八字中一起读，而不是只凭流年名称贴上“好年”或“坏年”。',
          'The natal chart is the birth configuration; a cycle is a roughly ten-year layer under a selected convention; an annual pillar adds a yearly layer. The excerpt calls for reading added symbols with the original chart, not labeling a year good or bad from its name.',
        ),
        w(
          '可以把它比作同一间屋子遇到不同季节：底图没有换，新来的条件却可能碰到不同位置。这个比喻解释的是层次，不是说现实一定按命盘安排变化；具体事件仍需要现实信息。',
          'As a metaphor, the same room encounters different seasons: the base remains while incoming conditions touch different parts. This explains layers, not inevitable events.',
        ),
      ],
      w(
        `${a.date}按立春分年，流年为${a.pillar}，年干对${chart.dayMaster}日主为${a.god}。${cycleText.zh}`,
        `${a.date}, using Lichun for the year boundary: ${a.pillar}; stem role relative to ${chart.dayMaster}: ${a.god}. ${cycleText.en}`,
      ),
      'cycles',
    ),
    section(
      w('今年具体增加了什么，要逐项对照', 'What does this selected year add?'),
      [
        w(
          `年干${a.pillar[0]}提供${a.god}这条关系线索；年支${a.pillar[1]}则与原局各支、已选大运支逐一比较。所以“十神主题”和“合冲落点”是两条信息，不能只保留一句笼统的年度建议。`,
          `Annual stem ${a.pillar[0]} adds the ${a.god} role; branch ${a.pillar[1]} is compared with natal branches and any active cycle. Role theme and branch positions are distinct pieces of information.`,
        ),
        w(
          '本版支持新增六合、六冲、六害配对。如果关联日支，可以回看感情章讨论的相处议题；关联月支，可以回看工作与安排。但“指向哪个议题”仍不是“哪件事必然发生”。下方相邻年份会分别重新计算，便于看到究竟是哪一项改变。',
          'This version checks added pair-combinations, clashes and harms. Day links can be read with relationship themes, month links with work themes, without predicting an event. Adjacent years are independently recalculated below.',
        ),
      ],
      linkText,
    ),
    section(
      w(
        '为什么“财年”不一定发财，“冲年”不一定出事',
        'Why role names and clashes do not determine outcomes',
      ),
      [
        w(
          '同一个财星，在不同原局里的位置和承接条件不同；同样一个冲，涉及的原局位置、已有合局和大运也可能不同。只用年干贴标签，等于跳过了“和谁发生关系、原来的条件怎样”这两问。本版尚未完整判断合化、三合新增关系与应期，因此不会把这份主题对照写成事件时间表。',
          'The same wealth role can meet different natal conditions; a clash can involve different positions and configurations. A year label alone skips both what it relates to and the existing context. Full transformations, added three-way combinations and event timing are not implemented.',
        ),
      ],
    ),
  ];
  return {
    wealth: moneySections,
    relationships: relationshipSections,
    health: healthSections,
    timing: timingSections,
  };
}
